---
abstract: 'Moose-based information scraper/fetcher for Twitpic'
author:
  - 'turugina <turugina@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Twitpic-Fetch
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Encode: 0
  IO::File: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Moose: 0
  Test::More: 0
  Text::Trim: 0
  URI: 0
  Web::Scraper: 0
version: 0.07
