--- #YAML:1.0
name:               WWW-Twitpic-Fetch
version:            0.03
abstract:           Moose-based information scraper/fetcher for Twitpic
author:
    - turugina <turugina@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    Encode:           0
    IO::File:         0
    List::MoreUtils:  0
    LWP::UserAgent:   0
    Moose:            0
    Test::More:       0
    Text::Trim:       0
    URI:              0
    Web::Scraper:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
